---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - flow.tgy.io
  resources:
  - taskflows
  - taskhandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flow.tgy.io
  resources:
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flow.tgy.io
  resources:
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - flow.tgy.io
  resources:
  - tasks/status
  verbs:
  - get
  - patch
  - update
